version: '3'

services:
  elk:
    build: .
    image: poc/elk
    container_name: poc-elk
    ports:
      - "5601:5601" # kibana port
      - "9200:9200" # elasticsearch port
      - "5044:5044" # beats port
      - "5000:5000" # json port